---
- hosts: appservers
  become_method: sudo
  become: yes
  remote_user: ubuntu

  vars:
    node_app_dir: /var/local/my_node_app


  environment:
    NVM_DIR: /var/local/nvm
    PATH: /var/local/nvm/versions/node/v4.2.1/bin:{{ ansible_env.PATH }}

  tasks:
  - name: Install reqired packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - curl
      - wget
  - name: Install nvm
    shell: >
      wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | sh
      creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh
  - name: Install node and set version
    shell: >
      /bin/bash -c "source ~/.nvm/nvm.sh && nvm install v14.19.2 && nvm alias default 14.19.2"
      creates=/home/{{ ansible_user_id }}/.nvm/alias
  - name: Clones the apllication from github
    git: 
      repo: https://github.com/DanielFrd8/Weight-Tracker.git
      dest: ~/
      archive: /tmp/Weight-Tracker.zip
  - name: Change directory to Weight-Tracker
    command: cd Weight-Tracker/
  - name: Install npm dependencies from package.json
    npm:
      ci: true
  - name: Install pm2 using npm
    npm:
      name: pm2
      global: yes
      state: present



  - name: Replaces the PORT in .env file
    replace: 
      path: /etc/hosts
      regexp: '"PORT"'
      replace: {{PORT}}
  - name: Replaces the HOST in .env file
    replace:
      path: /etc/hosts
      regexp: '"HOST"'
      replace: {{HOST}}
  - name: Replaces the HOST_URL in .env file
    replace:
      path: /etc/hosts
      regexp: '"HOST_URL"'
      replace: {{HOST_URL}}

  - name: Replaces the PGHOST in .env file
    replace:
      path: /etc/hosts
      regexp: '"PGHOST"'
      replace: {{PGHOST}}
  - name: Replaces the PGUSERNAME in .env file
    replace:
      path: /etc/hosts
      regexp: '"PGUSERNAME"'
      replace: {{PGUSERNAME}}
  - name: Replaces the PGDATABASE in .env file
    replace:
      path: /etc/hosts
      regexp: '"PGDATABASE"'
      replace: {{PGDATABASE}}
  - name: Replaces the PGPASSWORD in .env file
    replace:
      path: /etc/hosts
      regexp: '"PGPASSWORD"'
      replace: {{PGPASSWORD}}

  - name: Replaces the COOKIE_ENCRYPT_PWD in .env file
    replace:
      path: /etc/hosts
      regexp: '"COOKIE_ENCRYPT_PWD"'
      replace: {{COOKIE_ENCRYPT_PWD}}

  - name: Replaces the OKTA_ORG_URL in .env file
    replace:
      path: /etc/hosts
      regexp: '"OKTA_ORG_URL"'
      replace: {{OKTA_ORG_URL}}
  - name: Replaces the OKTA_CLIENT_ID in .env file
    replace:
      path: /etc/hosts
      regexp: '"OKTA_CLIENT_ID"'
      replace: {{OKTA_CLIENT_ID}}
  - name: Replaces the OKTA_CLIENT_SECRET in .env file
    replace:
      path: /etc/hosts
      regexp: '"OKTA_CLIENT_SECRET"'
      replace: {{OKTA_CLIENT_SECRET}}


  - name: Pm2 startup
    command: pm2 startup
  - name: Set pm2 environment 



    
